# Generated by Django 3.1 on 2020-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.CharField(default='', max_length=20),
        ),
    ]
